

services:
  # Servicio del que extienden los demás que contiene la configuración común
  base:
    image: chess-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      # Se montan los archivos de configuración de zsh
      - .zshrc:/root/.zshrc
      - .p10k.zsh:/root/.p10k.zsh

    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    environment:
      - PROJECT=chess

  # Servicio de desarrollo
  dev:
    extends: base
    ports:
      - "7000:7000"
    command: ["bun i && bun run start --host=0.0.0.0 --port=7000"]
    environment:
      - CONTAINER_NAME=chess-dev-container
    container_name: chess-dev-container

  # Servicio para construir la aplicación
  build:
    extends: base
    command: ["bun i && bun run build"]
    environment:
      - CONTAINER_NAME=chess-build-container
    container_name: chess-build-container
